[[key-principles]]
== Key principles and concepts of data publishing 

=== Types of biodiversity data 

Biodiversity data can encompass structured information data across any level of biodiversity—molecular, species or ecosystem. These data can be either primary biodiversity data, such as observations or collections at a specific time and place, or secondary, synthesized or interpreted data, which combine biodiversity and environmental data from different sources to interpret the real world as in a species distribution map. Although EIAs tend to present a considerable amount of secondary data, this information relies in turn on large volumes of primary biodiversity data, which is the focus of this document. 

The GBIF network specializes in bringing together ‘species occurrence data’ typically including, at a minimum, a scientific name, date and location of occurrence. Traditionally, these records have come from sources such as specimens from natural history collections, field work and monitoring surveys, but today other key sources include camera-trap images, environmental DNA sampling (eDNA) and citizen science projects.

While scientific name, date and location represent a minimum recommended level of information, records about the occurrence of organisms can also include other useful information, such as method used for the observation, abundance counts, habitat structure (like height, stratification, density), abiotic characteristics  (like, substrates, hydrology, climate) and associated information about land use and threats.  More information on data quality requirements can be found here: https://www.gbif.org/data-quality-requirements.

GBIF publishes four different classes of datasets (https://www.gbif.org/dataset-classes): metadata-only, checklist, occurrence and sampling-event. These classes represent increasingly richer levels of information rather than different types of data. Table 1 describes each class and examples of the type of information they include.  

`insert table-01`
.Steps to publishing data on www.gbif.org

=== Operating principles: Steps in the publishing process

GBIF provides a means of sharing biodiversity data, through the process known as *publishing*, that makes it universally accessible over the Internet, using simple tools and following standard procedures and protocols. Data publishing through the GBIF network follows a series of clear steps, shown in Figure 1. Each of these steps is described in more detail in the subsequent sections of this document.

This guide will help environmental assessment practitioners (EAPs), consultants and other interested and affected parties to choose the most suitable option or tool for publishing the primary biodiversity data they have gathered, as an integral part of the EIA process.

As a first step towards publishing biodiversity data, EAPs can seek assistance from the wide network of GBIF Participant Nodes. A full list of national, regional and thematic Participant Nodes can be found here: https://www.gbif.org/the-gbif-network. A majority of these nodes encourage, coordinate and assist in biodiversity data publishing activities within their respective jurisdictions and domains. If the EAP´s operations fall outside of the GBIF network e.g. in a country where there is no node, then helpdesk@gbif.org[the GBIF help desk] can provide additional support.

`insert figure-01`

==== Step 1:  Becoming a data publisher
Once there is agreement in an organization to share EIA data openly and freely, provisions must be in place to ensure that stakeholders in the process of data collection, curation and management agree to the terms by which data publishing takes place, and are properly acknowledged in their role. This includes agreement to the https://www.gbif.org/terms/data-publisher[Data Publisher Agreement] (the English version is valid for legal purposes) and understanding of the https://www.gbif.org/terms/data-user[Data User Agreement] that users of GBIF-mediated data must agree to before reusing data.

Data-holding organizations must register as data publishers, if they have not done so already. In the context of EIA data, this can either be the company planning the project, or the consultancy carrying out the biodiversity survey. Prospective publishers should register as publishers via https://www.gbif.org/become-a-publisher[this online form]. They are endorsed by Participant nodes where such an entity exists nationally (see this https://www.gbif.org/the-gbif-network[an up-to-date list of Participant countries]), or by a community endorsement process where no national node exists. The endorsement requests are handled by GBIF based on the details provided on the form. Registration as a data publisher will create a publisher page with which published datasets will be associated, including a description of the organization, logo and contact details.

==== Step 2. Data capture

Ensuring that data capture is standardized at point of collection will (a) make it easier for EAPs to collect and manage primary biodiversity data; (b) improve the consistency and utility of data collection, and (c) ensure that the data are collected in a consistent format, suitable for publishing using the GBIF infrastructure. GBIF uses the Darwin Core (DwC) and Ecological Metadata Language (EML) standards, which set out the structure and format of published datasets (learn more about https://www.gbif.org/standards[applicable standards]). GBIF also provides a https://www.gbif.org/dataset-classes[set of pre-configured Excel spreadsheets] that serve as templates for capturing checklist, occurrence and sampling-event data. These spreadsheets are simple tools that provide a common format and standard for collecting data, using consistent terminology, and can be completed with additional DwC terms to fit the data collection purpose. This makes it easier for data to be exchanged between users, compared between sites, and integrated into national and global biodiversity databases. No metadata template is provided as publishers can use the built-in metadata editor in GBIF’s data publication tool–the Integrated Publishing Toolkit (IPT) (see <<step-3>> below)–to populate the metadata. The IPT ensures that the data and metadata are in a valid XML format.

`insert table-02`
.Responses to key concerns raised by EIA data publishers

==== Step 3: Selecting a tool to prepare data for publishing

GBIF.org does not itself host data. The system relies on each data publisher maintaining their own datasets, and making them available online in a GBIF-supported format. It also relies on organizations letting GBIF know where to find and harvest the data, by registering the datasets. GBIF recommends using the [Integrated Publishing Toolkit](https://www.gbif.org/ipt) (IPT) to do this. Highly skilled publishers can also use an API to register datasets programmatically (contact the helpdesk@gbif.org[GBIF help desk] for more details).

Organizations may install the IPT if they have the capacity to host and maintain data on servers that always remain online, ensuring that the data that they share will have a persistent, stable point of access. Organizations that do not have this capacity, or do not wish to maintain their own installations, can choose one of the following options for data hosting:

. Data hosted at a national node (if the country is a GBIF Participant)
. Hosted by another GBIF Participant or data publisher
. Cloud-hosted IPTs maintained by GBIF Secretariat

The first two options provide a range of helpdesk services to potential publishers, while the final option provides very limited support to publishers. Potential publishers can request guidance from the helpdesk@gbif.org[GBIF help desk] on the most suitable option. Regardless of the hosting option selected, data publishers retain full control of the data, including the ability to correct and update datasets at any time. Data citations will always acknowledge the data publisher, irrespective of how or where the datasets are hosted.

The IPT is the most commonly-used tool and is maintained and developed by the GBIF Secretariat. IPTs can generate a Darwin Core Archive (DwC-A), the preferred exchange format, for each dataset and register them on GBIF. To use the IPT, data must already be digitized.  Acceptable file types include delimited text files (e.g. text files using comma or tab-separated values) or Microsoft Excel.  Database connections can also be made. If the IPT is to be hosted within the publishing institution, upon installation of the IPT, the publishing organization should register as the host. If the IPT is hosted elsewhere, the IPT administrator can add the publishing organization to the IPT using an IPT token that is issued upon endorsement of the publisher.

==== Step 4: Preparing data for publication

To share data through GBIF.org, publishers must collate or transform and describe existing datasets into a https://www.gbif.org/standards[standardized format]. This work may include additional processing, content editing and mapping the content of a dataset into one of the available data transfer formats.  Publishers thus play an essential role not simply in sharing datasets, but also in managing their quality, completeness and usefulness as well as ensuring their integration and value within GBIF’s global knowledge base. GBIF provides guidance on the https://www.gbif.org/data-quality-requirements[data quality requirements and recommendations]. The https://www.gbif.org/tools/data-validator[GBIF Data Validator] is a tool that lets publishers check datasets prior to publication and make recommendations on how datasets can be improved and cleaned by flagging, for example, duplicate identifiers, incomplete fields and recognized inconsistencies in formatting.

Publishers should use a precautionary approach and seek input from specialists on the publishing of precise locations of sensitive species, for example threatened or valuable species, when there are concerns that doing so could enable poaching or other threats to the species population. GBIF provides https://doi.org/10.15468/doc-5jp4-5g10[guidance on best practice for generalizing locations of sensitive data]. 

==== Step 5: Publishing data to GBIF

The GBIF IPT supports automatic registration in the GBIF network (see the https://github.com/gbif/ipt/wiki/IPT2ManualNotes.wiki[IPT manual]). If publishers are using an IPT, GBIF registers datasets when publishers click the ‘register’ button. Data should be published as soon as possible following the EIA. However, if there are concerns about commercial confidentiality or other time-sensitive issues, publication may be delayed or embargoed until the completion of a licensing process. 

Upon publication, data publishers must assign one of the three Creative Commons licences to any occurrence dataset:

* https://creativecommons.org/publicdomain/zero/1.0[CC0 1.0], for data made available for any use without any restrictions
* https://creativecommons.org/licenses/by/4.0[CC BY 4.0], for data made available for any use with appropriate attribution
* https://creativecommons.org/licenses/by-nc/4.0[CC BY-NC 4.0], for data made available for any non-commercial use with appropriate attribution.

Note that the CC-BY-NC license has a significant effect on the reusability of data, and that GBIF does not consider non-commercial use restrictions to be enforceable. GBIF encourages data publishers to choose the most open option possible.

==== Step 6:  Discovering and citing data through GBIF

Once registered, GBIF indexes datasets to facilitate access to the data by users. Datasets have their own page within www.gbif.org and can be found using the search function on the website or via the publishing organization’s pages, e.g. https://www.gbif.org/publisher/e5150835-f502-424c-b470-24dd496b1b18[EDP-Energias de Portugal]. Through the indexing process, records from published datasets may be discovered through complex searches, for example for all records of a particular species or groups of species in a given geographical area. The GBIF Data User Agreement requires proper citation of the data regardless of the chosen licence agreement. Through tracking of citations using Digital Object Identifiers (DOIs), GBIF provides publishers with key metrics on the onward use of their data cited in research and assessments, for example on this ‘activity’ tab from a dataset published by https://www.gbif.org/dataset/eba5d1aa-35dd-4f0c-b1dc-304f6b44d3b3/activity[SWECO]. Companies may use this information to demonstrate the value they have contributed to science and society through sharing data from EIAs.
